include: package:solid_lints/analysis_options.yaml

linter:
  rules:
    - prefer_single_quotes

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
    - avoid_unused_parameters: false

