name: unreal_remote_control
description: Simple UI For Unreal Engine Remote Control

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  hooks_riverpod: ^2.4.9
  http: ^1.2.0
  go_router: ^13.0.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.0
  solid_lints: ^0.1.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
