name: unreal_remote_control
description: Simple UI For Unreal Engine Remote Control

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_client: ^0.1.0-dev.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  provider: ^6.0.5
  uuid: ^3.0.7
  fluent_ui: ^4.6.1
  system_theme: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
