name: unreal_remote_control
description: Simple UI For Unreal Engine Remote Control

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.5.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
