name: Release bundled apps

on:
  push:
    branches:
      - master

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Codegen
        run: flutter pub get && flutter pub run build_runner build

      - name: Build Flutter app for macOS
        run: flutter build macos --release

      - name: Set executable permission for macOS app
        run: chmod +x build/macos/Build/Products/Release/unreal_remote_control.app/Contents/MacOS/unreal_remote_control

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unreal-Remote-Control-UI-macos
          path: build/macos/Build/Products/Release/*.app

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Codegen
        run: flutter pub get && flutter pub run build_runner build

      - name: Build Flutter app for Windows
        run: flutter build windows --release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unreal-Remote-Control-UI-windows
          path: build/windows/runner/Release/*.exe
